title: DAOcast
author: Danilo & Stratis
description: Exploring the frontiers of Decentralized Autonomous Organizations and Distributed Self-Organizing..

highlighter: null
permalink: /:title

url: daocast.github.io
baseurl:

# Custom options:
# color_scheme: azul|ruby|amber|avocado
color_scheme: azul
