title: DAOcast
author: Aigars Dzerviniks
description: Exploring the frontiers of Decentralized Autonomous Organizations.

highlighter: null
permalink: /:title

url: daocast.github.io
baseurl:

# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado
